### ISSUE TITLE
Add .gitignore file to repository root

### ISSUE THREAD

**Issue by sudhir-b** [EAB1995/ds#1]
Adding a [.gitignore](https://git-scm.com/docs/gitignore) file with at least the following content will mean that you won't have the `__pycache__` folder or any `.pyc` hanging around. The `.pyc` files contain compiled python bytecode and this will vary for different users of a project depending on what Python version they've got installed (and possibly also what OS they're using - but not sure about that one), so in general they're not useful files to include in a repository.

```
__pycache__
*.pyc
```

**Comment by EAB1995** [comment]
Having a bit of trouble with this one - 

I started by making the .gitignore folder with mikdir 

I moved the __pycache__ into it with mv 

I pushed it to Github, but the old __pycache__ is still there

rm -r __pycache__ on my branch and push 

I could just delete the __pycache__ on the branch through the browser interface on Github but I'm trying to stick to the gitbash shell/command line for best practice...

**Comment by sudhir-b** [comment]
Fixed by #6
