### ISSUE TITLE
Handle invalid user input

### ISSUE THREAD

**Issue by sudhir-b** [EAB1995/ds#3]
Everywhere where user input is accepted, there should be a handler for any invalid input - for example for the intro:

```
    a1 = input("--[")
    if a1 == "1":
        abbot.add_inventory(slug_pistol)
        prt_txt("\nLT MILLER TAKES THE RAY GUN.")
        miller.add_inventory(ray_gun)
    elif a1 == "2":
        miller.add_inventory(slug_pistol)
        prt_txt("\nLT ABBOT TAKES THE RAY GUN.")
        abbot.add_inventory(ray_gun)
```

there should be a way of rejecting invalid user input and asking the user again for a valid choice

**Comment by EAB1995** [comment]
Added function take_in(str) that checks input against string of valid inputs, and recursively calls itself until a correct input is given before returning it
